services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped
