services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - API_KEY=YOUR_API_KEY
      - REDIS_URL=redis://redis:6379
